# Generated by Django 5.1.4 on 2025-03-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='guide',
        ),
    ]
