# Generated by Django 5.1.4 on 2025-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_trip_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='SecretKey',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
