# Generated by Django 5.1.4 on 2024-12-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
