# Generated by Django 5.1.4 on 2025-02-17 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuideApp', '0001_initial'),
        ('main', '0003_alter_trip_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='guide',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='GuideApp.guide'),
        ),
    ]
