# Generated by Django 5.1.4 on 2025-03-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registration_secretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='equipment_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='meeting_point_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
