# Generated by Django 5.1.4 on 2025-03-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trip_equipment_needed_trip_meeting_point_coordinates'),
        ('main', '0005_auto_replace_id_with_notes'),
    ]

    operations = [
    ]
