# Generated by Django 5.1.4 on 2025-04-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20250330_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponn_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
