# Generated by Django 5.1.4 on 2025-04-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_coupon_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='trip_gallery/')),
                ('caption', models.CharField(blank=True, max_length=150, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Description for accessibility', max_length=150, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.trip')),
            ],
            options={
                'verbose_name': 'Trip Gallery Image',
                'verbose_name_plural': 'Trip Gallery Images',
            },
        ),
    ]
